### ISSUE TITLE
Incorrect argument in INokiaIAPService.getPurchases() call

### ISSUE THREAD

**Issue by mikosik** [microsoft/nokia-x-in-app-payment-samples#1]
I'm trying to learn how to use INokiaIAPService.

I browsed this project and found out that class Payment has following call

```
 Bundle purchases = npay.getPurchases(1, activity.getPackageName(), ITEM_TYPE_INAPP, productBundle, null);
```

First argument is 1 but INokiaIAPService documentation states that it should be 3.
Is it bug in documentation or in this project?

**Comment by jtjk** [comment]
Hi, 

It is "bug" in project. It should be 3, but actually it works with 1 as well. 

Br,
Janne Koskinen
